## Working with Numpy
## Gabriel Migliore
## Python 3
## Spring 2022

## 1. Create a 2 by 2 Numpy array with elements

In [1]:
import numpy as np

In [12]:
array1=np.array([(10,20),(30,40)], dtype=int)

In [13]:
array1

array([[10, 20],
       [30, 40]])

In [17]:
array2=array1*array1

In [18]:
array2

array([[ 100,  400],
       [ 900, 1600]])

In [19]:
array2=np.add(array1,100)

In [20]:
array2

array([[110, 120],
       [130, 140]])

In [21]:
array2=array1*5

In [22]:
array2

array([[ 50, 100],
       [150, 200]])

In [23]:
array2=np.sqrt(array1)

In [24]:
array2

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

## 2. Create a 3 by 3 array

In [56]:
array3=np.linspace(3,27,9)
array3=array3.astype(int)
array3=array3.reshape(3,3)

In [57]:
array3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [64]:
array4=np.linspace(10,20,9)
array4=array4.reshape(3,3)

In [67]:
array4

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [69]:
array5=array3*array4

In [70]:
array5

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

## 3. Five .npy files

In [73]:
array1=np.load('process1.npy')
array2=np.load('process2.npy')
array3=np.load('process3.npy')
array4=np.load('process4.npy')
array5=np.load('process5.npy')

In [76]:
array6=np.vstack((array1,array2,array3,array4,array5))

In [77]:
array6

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [79]:
array6.mean(axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])